# Generated by Django 2.2.3 on 2020-03-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatcontent', '0006_auto_20200314_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, null=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('altname', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('measure', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('currency', models.IntegerField(blank=True, choices=[(1, '₽')], db_index=True, null=True)),
                ('old_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=13, null=True)),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=13, null=True)),
                ('dj_info', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mini_info', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Товары - товар/услуга',
                'verbose_name_plural': 'Товары - товары/услуги',
            },
        ),
        migrations.CreateModel(
            name='ProductsCats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatcontent.Containers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
