# Generated by Django 2.2.3 on 2020-03-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscats',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatcontent.Blocks'),
        ),
    ]
