# Generated by Django 2.2.3 on 2020-04-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200402_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertiesvalues',
            name='int_value',
        ),
        migrations.AddField(
            model_name='propertiesvalues',
            name='digit_value',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=13, null=True),
        ),
    ]
