# Generated by Django 2.2.3 on 2020-04-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200402_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ptype',
            field=models.IntegerField(blank=True, choices=[(1, 'Выпадающий список select'), (2, 'Выпадающий список с множественным выбором multiselect'), (3, 'Выбор из вариантов radio'), (4, 'Множественный выбор из вариантов checkbox')], db_index=True, null=True),
        ),
    ]
