# Generated by Django 2.2.3 on 2020-04-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_property_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
