# Generated by Django 2.2.3 on 2020-06-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_property_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('currency', models.IntegerField(blank=True, choices=[(1, '₽'), (2, '$')], db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.IntegerField(blank=True, choices=[(1, '₽'), (2, '$')], db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.IntegerField(blank=True, choices=[(1, 'шт'), (2, 'л')], db_index=True, null=True)),
                ('cost', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=13, null=True)),
                ('cost_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CostsTypes')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
