# Generated by Django 2.2.3 on 2020-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200627_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='min_count',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Минимальное кол-во для заказа'),
        ),
        migrations.AddField(
            model_name='products',
            name='multiplicity',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Кратность товара, по сколько будет добавляться +/-'),
        ),
    ]
