# Generated by Django 2.2.3 on 2020-12-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201212_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='search_facet',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отображать в фильтрах для поиска'),
        ),
    ]
