# Generated by Django 2.2.3 on 2022-01-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220122_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock_info',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Текстовая информация об остатках'),
        ),
    ]
