# Generated by Django 2.2.3 on 2023-03-05 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatcontent', '0012_auto_20220418_1222'),
        ('products', '0016_products_stock_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatcontent.Blocks'),
        ),
    ]
