# Generated by Django 2.2.3 on 2021-06-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatcontent', '0011_auto_20210526_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наименование контрагента')),
                ('code', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Код контрагента')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email')),
                ('site', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Сайт')),
                ('info1', models.TextField(blank=True, null=True, verbose_name='Информация 1')),
                ('info2', models.TextField(blank=True, null=True, verbose_name='Информация 1')),
                ('info3', models.TextField(blank=True, null=True, verbose_name='Информация 1')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flatcontent.Blocks', verbose_name='Привязка к менюшке')),
            ],
            options={
                'verbose_name': 'Телефоны 8800 - Телефон 8800',
                'verbose_name_plural': 'Телефоны 8800 - Телефоны 8800',
            },
        ),
    ]
