# Generated by Django 2.2.3 on 2019-12-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Афиша - Места', 'verbose_name_plural': 'Афиша - Места'},
        ),
        migrations.AlterModelOptions(
            name='revents',
            options={'verbose_name': 'Афиша - События', 'verbose_name_plural': 'Афиша - События'},
        ),
        migrations.AlterModelOptions(
            name='rgenres',
            options={'verbose_name': 'Афиша - Жанры', 'verbose_name_plural': 'Афиша - Жанры'},
        ),
        migrations.AlterModelOptions(
            name='rseances',
            options={'verbose_name': 'Афиша - Сеансы', 'verbose_name_plural': 'Афиша - Сеансы'},
        ),
        migrations.AlterModelOptions(
            name='rubrics',
            options={'verbose_name': 'Афиша - Рубрикатор мест', 'verbose_name_plural': 'Афиша - Рубрикатор мест'},
        ),
    ]
