# Generated by Django 2.2.3 on 2022-02-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0015_auto_20220123_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер полиса/заказа')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ФИО')),
                ('birthday', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения')),
                ('insurance_sum', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Общая страховая сумма')),
                ('insurance_program', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Страховая программа')),
                ('from_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Период страхования с')),
                ('to_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Период страхования до')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Orders', verbose_name='Ссылка на заказ')),
            ],
            options={
                'verbose_name': 'Страховка - Полис',
                'verbose_name_plural': 'Страховка - Полисы',
            },
        ),
    ]
