# Generated by Django 2.2.3 on 2022-02-25 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polis',
            name='already_safe',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Уже застрахован'),
        ),
        migrations.CreateModel(
            name='PolisMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Имя застрахованного')),
                ('birthday', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения застрахованного')),
                ('polis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polis.Polis')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
