# Generated by Django 2.2.3 on 2022-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polis', '0003_polis_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='polis',
            name='days',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество дней'),
        ),
    ]
