# Generated by Django 2.2.3 on 2022-11-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_auto_20221116_1948'),
        ('polis', '0004_polis_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='polismember',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passport.Passport', verbose_name='Паспорт страхуемого'),
        ),
        migrations.AlterField(
            model_name='polis',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер полюса/заказа'),
        ),
        migrations.AlterField(
            model_name='polis',
            name='ptype',
            field=models.IntegerField(blank=True, choices=[(1, 'Хоккей'), (2, 'Круиз')], db_index=True, null=True, verbose_name='Тип полюса (для формы)'),
        ),
    ]
