# Generated by Django 2.2.3 on 2021-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='class_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Класс css'),
        ),
    ]
