# Generated by Django 2.2.3 on 2020-12-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('postalCode', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('subdistrict', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('houseNumber', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('addressLines', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('additionalData', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=25, max_digits=30, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=25, max_digits=30, null=True)),
                ('place', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Адреса - адрес объекта',
                'verbose_name_plural': 'Адреса - адреса объектов',
            },
        ),
    ]
