# Generated by Django 2.2.3 on 2021-10-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Потенциально уникальный идентификатор'),
        ),
    ]
