# Generated by Django 2.2.3 on 2021-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabber', '0002_firebasetokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasetokens',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='IP пользователя'),
        ),
    ]
