# Generated by Django 2.2.3 on 2021-11-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabber', '0003_firebasetokens_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
