# Generated by Django 2.2.3 on 2022-08-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabber', '0004_registrations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasetokens',
            name='apns_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Токен APNS приложения пользователя'),
        ),
    ]
