# Generated by Django 2.2.3 on 2022-12-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabber', '0005_firebasetokens_apns_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='hash_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Хэш логин + пароль'),
        ),
    ]
