# Generated by Django 2.2.3 on 2023-02-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabber', '0006_registrations_hash_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('jid_owner', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Владелец контакта')),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Отображаемое имя контакта')),
                ('given_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Имя контакта')),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Отчество контакта')),
                ('family_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Фамилия контакта')),
                ('company', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Компания контакта')),
                ('job_title', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Должность')),
                ('emails', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email список')),
                ('phones', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Cписок телефонов')),
                ('postal_addresses', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Почтовый адрес')),
                ('birthday', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='День рождения')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
