# Generated by Django 2.2.3 on 2020-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('domain_pk', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Домен на каждый сайт из settings.py')),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Привязка к типу модели')),
                ('model_pk', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID экземпляра модели')),
                ('field', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Поле, которое переводим')),
                ('value', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Значение поля (перевод)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Если поле большое, то это перевод без индекса')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
    ]
