# Generated by Django 2.2.3 on 2021-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UITranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='css класс элемента')),
                ('domain_pk', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Домен на каждый сайт из settings.py')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Перевод')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
