# Generated by Django 2.2.3 on 2021-04-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_uitranslate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uitranslate',
            options={'verbose_name': 'Перевод UI', 'verbose_name_plural': 'Переводы UI'},
        ),
    ]
