# Generated by Django 2.2.3 on 2023-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Имя хоста')),
                ('start_ip', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Начальный ip адрес')),
                ('end_ip', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Конечный ip адрес')),
            ],
            options={
                'verbose_name': 'NetTools - IPRange',
                'verbose_name_plural': 'NetTools - IPRange',
            },
        ),
    ]
