# Generated by Django 2.2.3 on 2021-05-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_testscenarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название сайта')),
                ('url', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Ссылка на главную страницу сайта')),
            ],
            options={
                'verbose_name': 'Роботы - Сайт',
                'verbose_name_plural': 'Роботы - Сайты',
            },
        ),
        migrations.CreateModel(
            name='SearchQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Поисковой запрос')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.Sites', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Роботы - Поисковой запрос',
                'verbose_name_plural': 'Роботы - Поисковые запросы',
            },
        ),
        migrations.CreateModel(
            name='RobotProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название профиля (папки)')),
                ('user_agent', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Строка user_agent (браузер)')),
                ('resolution', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Разрешение экрана')),
                ('yandex_login', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('yandex_passwd', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.Robots')),
            ],
            options={
                'verbose_name': 'Роботы - Профиль',
                'verbose_name_plural': 'Роботы - Профили',
            },
        ),
        migrations.AddField(
            model_name='testscenarios',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.Sites', verbose_name='Сайт'),
        ),
    ]
