# Generated by Django 2.2.3 on 2020-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, null=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gw', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Шлюз, через который переадресовываем')),
                ('dest', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Куда переадресовываем (номер телефона)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('price', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Цена для тарификации')),
                ('price_unit', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество секунд для цены тарификации')),
            ],
            options={
                'verbose_name': 'Freeswitch - Переадресация',
                'verbose_name_plural': 'Freeswtich - Переадресации',
            },
        ),
    ]
