# Generated by Django 2.2.3 on 2020-01-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeswitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirects',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наш телефон'),
        ),
    ]
