# Generated by Django 2.2.3 on 2020-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeswitch', '0006_phoneswhitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, null=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('userid', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='fsuser',
            options={'verbose_name': 'Freeswitch - Пользователь', 'verbose_name_plural': 'Freeswtich - Польозватели'},
        ),
        migrations.AlterModelOptions(
            name='phoneswhitelist',
            options={'verbose_name': 'Freeswitch - Белый список телефонов', 'verbose_name_plural': 'Freeswtich - Белый список телефонов'},
        ),
    ]
