# Generated by Django 2.2.3 on 2020-02-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeswitch', '0008_auto_20200212_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneswhitelist',
            name='desc',
        ),
    ]
