# Generated by Django 2.2.3 on 2020-02-12 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeswitch', '0009_remove_phoneswhitelist_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneswhitelist',
            options={'verbose_name': 'Freeswitch - Телефоны CRM', 'verbose_name_plural': 'Freeswtich - Телефоны CRM'},
        ),
        migrations.AlterField(
            model_name='fsuser',
            name='personal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_fs_user', to='freeswitch.PersonalUsers'),
        ),
        migrations.AlterField(
            model_name='fsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_fs_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
