# Generated by Django 2.2.3 on 2020-10-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeswitch', '0010_auto_20200212_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalusers',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalusers',
            name='phone_confirmed',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Телефон подтвержден'),
        ),
        migrations.AlterField(
            model_name='fsuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='personalusers',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='phoneswhitelist',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='redirects',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
