# Generated by Django 2.2.3 on 2021-03-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeswitch', '0011_auto_20201023_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalusers',
            name='userkey',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Уникальный ид пользователя (замена userid)'),
        ),
    ]
