# Generated by Django 2.2.3 on 2021-03-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeswitch', '0012_personalusers_userkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrcsv',
            name='personal_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Ид пользователя на сайте (сайты разыне - с префиксом)'),
        ),
    ]
