# Generated by Django 2.2.3 on 2021-05-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20200517_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name': 'Promotion - поисковый запрос', 'verbose_name_plural': 'Promotion - поисковые запросы'},
        ),
    ]
