# Generated by Django 2.2.3 on 2022-02-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0005_shopper_phone_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения')),
                ('series', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Серия паспорта')),
                ('number', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Номер паспорта')),
                ('issued', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Кем выдан')),
                ('issued_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Когда выдан')),
                ('registration', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Адрес регистрации')),
                ('shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.Shopper', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь - Паспортные данные',
                'verbose_name_plural': 'Пользователь - Паспортные данные',
            },
        ),
    ]
