# Generated by Django 2.2.3 on 2022-02-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='ptype',
            field=models.IntegerField(blank=True, choices=[(1, 'Паспорт РФ'), (2, 'Загранпаспорт')], db_index=True, null=True, verbose_name='Тип паспорта: рф/загран'),
        ),
    ]
