# Generated by Django 2.2.3 on 2022-11-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_passport_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='ptype',
            field=models.IntegerField(blank=True, choices=[(1, 'Паспорт гражданина РФ'), (2, 'Загранпаспорт гражданина РФ')], db_index=True, null=True, verbose_name='Тип паспорта: рф/загран'),
        ),
    ]
