# Generated by Django 2.2.3 on 2022-12-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_auto_20221116_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='ptype',
            field=models.IntegerField(blank=True, choices=[(1, 'Паспорт гражданина РФ'), (2, 'Загранпаспорт гражданина РФ'), (3, 'Свидетельство о рождении')], db_index=True, null=True, verbose_name='Тип паспорта: рф/загран'),
        ),
    ]
