# Generated by Django 2.2.3 on 2019-08-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatcontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='blank',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='icon',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='keywords',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
