# Generated by Django 2.2.3 on 2019-12-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatcontent', '0002_auto_20190825_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocks',
            options={'verbose_name': 'Стат.контент - Блоки', 'verbose_name_plural': 'Стат.контент - Блоки'},
        ),
        migrations.AlterModelOptions(
            name='containers',
            options={'verbose_name': 'Стат.контент - Контейнеры', 'verbose_name_plural': 'Стат.контент - Контейнеры'},
        ),
        migrations.AlterModelOptions(
            name='linkcontainer',
            options={'verbose_name': 'Стат.контент - Линковка меню к контейнерам', 'verbose_name_plural': 'Стат.контент - Линковка меню к контейнерам'},
        ),
    ]
