# Generated by Django 2.2.3 on 2020-01-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatcontent', '0003_auto_20191203_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
