# Generated by Django 2.2.3 on 2020-03-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatcontent', '0005_auto_20200112_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='blank',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
