# Generated by Django 2.2.3 on 2020-04-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatcontent', '0006_auto_20200314_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='blank',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='containers',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='linkcontainer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
