# Generated by Django 2.2.3 on 2020-12-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatcontent', '0008_containers_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='class_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Класс css'),
        ),
    ]
