# Generated by Django 2.2.3 on 2021-04-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatcontent', '0009_blocks_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocks',
            options={'permissions': (('seo_fields', 'Заполнение сео-полей'),), 'verbose_name': 'Стат.контент - Блоки', 'verbose_name_plural': 'Стат.контент - Блоки'},
        ),
    ]
