# Generated by Django 2.2.3 on 2020-06-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demonology', '0007_delete_schedule'),
        ('binary_com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('daemon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demonology.Daemon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event', models.IntegerField(blank=True, choices=[(1, 'Стратегия Bollinger'), (2, 'Стратегия Random')], db_index=True, null=True)),
                ('start', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Начало события')),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершение события')),
            ],
            options={
                'verbose_name': 'Бинари - Расписание для робота',
                'verbose_name_plural': 'Бинари - Расписания для робота',
            },
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.AddField(
            model_name='robots',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='binary_com.Schedule'),
        ),
    ]
