# Generated by Django 2.2.3 on 2020-06-11 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('binary_com', '0002_auto_20200611_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robots',
            options={'verbose_name': 'Бинари - Робот', 'verbose_name_plural': 'Бинари - Роботы'},
        ),
        migrations.RemoveField(
            model_name='robots',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='robot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='binary_com.Robots', verbose_name='Робот'),
        ),
    ]
