# Generated by Django 2.2.3 on 2020-08-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary_com', '0003_auto_20200611_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='symbol',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
