# Generated by Django 2.2.3 on 2021-10-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20211024_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='телефон с тире')),
                ('digits', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='тел без тире')),
                ('ctype', models.IntegerField(blank=True, choices=[(1, 'phone'), (2, 'site'), (3, 'email'), (4, 'twitter'), (5, 'facebook'), (6, 'instagram')], db_index=True, null=True)),
                ('comment', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Комментарий к телефону')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('main_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.MainCompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
