# Generated by Django 2.2.3 on 2021-10-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='digits',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.AddField(
            model_name='contact',
            name='indexed_value',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Значение для индексации'),
        ),
        migrations.AddField(
            model_name='contact',
            name='value',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Значение в человеческом виде'),
        ),
    ]
