# Generated by Django 2.2.3 on 2021-10-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20211025_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Значение в человеческом виде'),
        ),
    ]
