# Generated by Django 2.2.3 on 2021-10-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20211025_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='indexed_value',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Значение для индексации'),
        ),
    ]
