# Generated by Django 2.2.3 on 2021-11-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20211025_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincompany',
            name='img_view',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Изображение для компании'),
        ),
    ]
