# Generated by Django 2.2.3 on 2019-12-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
