# Generated by Django 2.2.3 on 2020-09-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='show_in_table',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Показывать в таблице принудительно'),
        ),
    ]
