# Generated by Django 2.2.3 on 2020-07-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_extrafields_extrainfo_extravalues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extravalues',
            old_name='name',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='extravalues',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ExtraFields'),
        ),
    ]
