# Generated by Django 2.2.3 on 2020-07-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200713_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrafields',
            options={'default_permissions': [], 'verbose_name': 'Доп. поле пользователя', 'verbose_name_plural': 'Доп. поля пользователей'},
        ),
        migrations.AlterModelOptions(
            name='extrainfo',
            options={'default_permissions': [], 'verbose_name': 'Доп. поле пользователя', 'verbose_name_plural': 'Доп. поля пользователей'},
        ),
        migrations.AlterModelOptions(
            name='extravalues',
            options={'default_permissions': [], 'verbose_name': 'Значение на доп. поле пользователя', 'verbose_name_plural': 'Значниея на доп. поля пользователей'},
        ),
    ]
