# Generated by Django 2.2.3 on 2020-07-14 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingjoint',
            name='line',
        ),
        migrations.AddField(
            model_name='joint',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Line', verbose_name='Номер линии, например, 913A'),
        ),
    ]
