# Generated by Django 2.2.3 on 2020-07-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0003_auto_20200715_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Договор, например, UOP')),
            ],
            options={
                'verbose_name': 'Сварочные соединения - Договор',
                'verbose_name_plural': 'Сварочные соединения - Договоры',
            },
        ),
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Сварочные соединения - Установка', 'verbose_name_plural': 'Сварочные соединения - Установки'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Сварочные соединения - Компания', 'verbose_name_plural': 'Сварочные соединения - Компании'},
        ),
        migrations.AlterModelOptions(
            name='joint',
            options={'verbose_name': 'Сварочные соединения - Стык', 'verbose_name_plural': 'Сварочные соединения - Стыки'},
        ),
        migrations.AlterModelOptions(
            name='jointwelder',
            options={'default_permissions': [], 'verbose_name': 'Сварочные соединения - Сварщик стыка', 'verbose_name_plural': 'Сварочные соединения - Сварщики стыков'},
        ),
        migrations.AlterModelOptions(
            name='jointype',
            options={'verbose_name': 'Сварочные соединения - Свариваемый элемент', 'verbose_name_plural': 'Сварочные соединения - Свариваемые элементы'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': 'Сварочные соединения - Линия', 'verbose_name_plural': 'Сварочные соединения - Линии'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Сварочные соединения - Материал (сталь)', 'verbose_name_plural': 'Сварочные соединения - Материалы (сталь)'},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'verbose_name': 'Сварочные соединения - Схема', 'verbose_name_plural': 'Сварочные соединения - Схемы'},
        ),
        migrations.AlterModelOptions(
            name='titul',
            options={'verbose_name': 'Сварочные соединения - Титул', 'verbose_name_plural': 'Сварочные соединения - Титулы'},
        ),
        migrations.AlterModelOptions(
            name='welder',
            options={'verbose_name': 'Сварочные соединения - Сварщик', 'verbose_name_plural': 'Сварочные соединения - Сварщики'},
        ),
        migrations.AlterModelOptions(
            name='weldingjoint',
            options={'verbose_name': 'Сварочное соединение - Бланк-заявка', 'verbose_name_plural': 'Сварочные соединения - Бланк-заявки'},
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, '*')], db_index=True, null=True, verbose_name='Категория, например I'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='control_result',
            field=models.IntegerField(blank=True, choices=[(1, 'Вырезать'), (2, 'Годен'), (3, 'Ремонт'), (4, 'УЗК'), (5, 'Пересвет'), (6, 'Брак')], db_index=True, null=True, verbose_name='Результат контроля, например, Вырезать'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='control_type',
            field=models.IntegerField(blank=True, choices=[(1, 'РК'), (2, 'УЗК'), (3, 'ВИК'), (4, 'РК-УЗК-ЦД'), (5, 'РК/УЗК'), (6, 'УК'), (7, 'ПВК'), (8, '*')], db_index=True, null=True, verbose_name='Вид контроля, например, РК'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='welding_conn_view',
            field=models.IntegerField(blank=True, choices=[(1, 'С17'), (2, 'У20'), (4, 'С17/У20'), (5, 'У19')], db_index=True, null=True, verbose_name='Вид сварного соединения, например, C17'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='welding_type',
            field=models.IntegerField(blank=True, choices=[(1, 'РАД'), (2, 'РД'), (3, 'РАД/РД')], db_index=True, null=True, verbose_name='Тип сварки, например, РД'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='workshift',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '-')], db_index=True, null=True, verbose_name='Номер, смены, например, 1'),
        ),
        migrations.AddField(
            model_name='weldingjoint',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Contract', verbose_name='Договор, например, UOP'),
        ),
    ]
