# Generated by Django 2.2.3 on 2020-07-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0004_auto_20200715_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfGuarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Гарантийное письмо на сварщика, например, №38УК/093-19 от 18.11.19г о сроках проведения мех.испытаний до 25.02.20')),
                ('letter', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Путь до файла с самим письмом')),
            ],
            options={
                'verbose_name': 'Сварочные соединения - Гарантийное письмо на сварщика',
                'verbose_name_plural': 'Сварочные соединения - Гарантийные письма на сварщиков',
            },
        ),
        migrations.RemoveField(
            model_name='weldingjoint',
            name='on_balance',
        ),
        migrations.AddField(
            model_name='welder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Company', verbose_name='Находится на объекте, например, ГФУ'),
        ),
        migrations.AddField(
            model_name='welder',
            name='notice',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Примечание, например, нет закл. ВИК, РК, ДЛ'),
        ),
        migrations.AlterField(
            model_name='welder',
            name='stigma',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Клеймо, например, 9SZN'),
        ),
        migrations.CreateModel(
            name='Vik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер, например, 2226 или D/5')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата для номера, например, 20/10/2018')),
                ('welder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Welder', verbose_name='Сварщик')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NAX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер удостоверения, например, ВСР-1ГАЦ-I-08121')),
                ('best_before', models.DateField(blank=True, db_index=True, null=True, verbose_name='НАКС годен до, например, 27/04/20')),
                ('welding_type', models.IntegerField(blank=True, choices=[(1, 'РАД'), (2, 'РД'), (3, 'РАД/РД')], db_index=True, null=True, verbose_name='Тип сварки, например, РД')),
                ('half_year_mark', models.DateField(blank=True, db_index=True, null=True, verbose_name='Полугодовая отметка, например, 12/10/19')),
                ('identification', models.IntegerField(blank=True, choices=[(1, 'офис Иркутск')], db_index=True, null=True, verbose_name='Место идентификации, например, офис Иркутск')),
                ('acl', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Допуск')),
                ('welder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Welder', verbose_name='Сварщик')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MechTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер для мехиспытания, например, 6/2-ТПС')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата для мехиспытания, например, 29/10/18')),
                ('welder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Welder', verbose_name='Сварщик')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoldingKSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('standard_size', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Типоразмер, например, 100х300')),
                ('spent_length', models.IntegerField(blank=True, choices=[(1, 0.3)], db_index=True, null=True, verbose_name='Затрачиваемая длина 150мм*2, например, 0.3')),
                ('number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер КСС, например, КСС-2226/1')),
                ('state', models.IntegerField(blank=True, choices=[(1, 'TT')], db_index=True, null=True, verbose_name='ТТ/МК, например, ТТ')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Material', verbose_name='Материал - сталь, например, 12Х18Н10Т')),
                ('welder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Welder', verbose_name='Сварщик')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControlK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='УЗК/РК номер, например, 13-РК')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата для УЗК/РК номера, например, 10/20/2018')),
                ('welder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Welder', verbose_name='Сварщик')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер для допускного листа, например, 17-18')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата для допускного листа, например, 30/10/18')),
                ('welder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Welder', verbose_name='Сварщик')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
