# Generated by Django 2.2.3 on 2020-07-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0005_auto_20200717_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welder',
            old_name='location',
            new_name='company',
        ),
    ]
