# Generated by Django 2.2.3 on 2020-07-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0007_letterofguarantee_welder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingkss',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'ТТ / МК'), (2, 'МК'), (3, 'ТТ'), (4, 'Уволен'), (5, 'Увольняется'), (6, 'Уехал')], db_index=True, null=True, verbose_name='ТТ/МК, например, ТТ'),
        ),
        migrations.AlterField(
            model_name='nax',
            name='half_year_mark',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Полугодовая отметка, например, есть'),
        ),
    ]
