# Generated by Django 2.2.3 on 2020-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0008_auto_20200718_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionsheet',
            options={'verbose_name': 'Сварщики - Лист допуска', 'verbose_name_plural': 'Сварщики - Листы допуска'},
        ),
        migrations.AlterModelOptions(
            name='controlk',
            options={'verbose_name': 'Сварщики - УЗК/РК контроль', 'verbose_name_plural': 'Сварщики - УЗК/РК контроль'},
        ),
        migrations.AlterModelOptions(
            name='holdingkss',
            options={'verbose_name': 'Сварщики - Проведение КСС', 'verbose_name_plural': 'Сварщики - Проведения КСС'},
        ),
        migrations.AlterModelOptions(
            name='letterofguarantee',
            options={'verbose_name': 'Сварщики - Гарантийное письмо', 'verbose_name_plural': 'Сварщики - Гарантийные письма'},
        ),
        migrations.AlterModelOptions(
            name='mechtest',
            options={'verbose_name': 'Сварщики - Мехиспытание', 'verbose_name_plural': 'Сварщики - Мехиспытания'},
        ),
        migrations.AlterModelOptions(
            name='nax',
            options={'verbose_name': 'Сварщики - Аттестат (НАКС)', 'verbose_name_plural': 'Сварщики - Аттестаты (НАКС)'},
        ),
        migrations.AlterModelOptions(
            name='vik',
            options={'verbose_name': 'Сварщики - Акт ВИК', 'verbose_name_plural': 'Сварщики - Акты ВИК'},
        ),
        migrations.AlterModelOptions(
            name='welder',
            options={'verbose_name': 'Сварщики - Сварщик', 'verbose_name_plural': 'Сварщики - Сварщики'},
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='dinc',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=12, max_digits=17, null=True, verbose_name='D-inc на человека или стык, например, 10324,748031496063'),
        ),
    ]
