# Generated by Django 2.2.3 on 2020-07-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0009_auto_20200720_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Справочники - Установка', 'verbose_name_plural': 'Справочники - Установки'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Справочники - Компания', 'verbose_name_plural': 'Справочники - Компании'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Справочники - Договор', 'verbose_name_plural': 'Справочники - Договоры'},
        ),
        migrations.AlterModelOptions(
            name='jointype',
            options={'verbose_name': 'Справочники - Свариваемый элемент', 'verbose_name_plural': 'Справочники - Свариваемые элементы'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Справочники - Материал (сталь)', 'verbose_name_plural': 'Справочники - Материалы (сталь)'},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'verbose_name': 'Справочники - Схема', 'verbose_name_plural': 'Справочники - Схемы'},
        ),
        migrations.AlterModelOptions(
            name='titul',
            options={'verbose_name': 'Справочники - Титул', 'verbose_name_plural': 'Справочники - Титулы'},
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='repair',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], db_index=True, null=True, verbose_name='Ремонт, например, 2 (второй ремонт)'),
        ),
    ]
