# Generated by Django 2.2.3 on 2020-07-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200402_2127'),
        ('weld', '0010_auto_20200722_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Позиция файла')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Files', verbose_name='Файл для линии')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Справочники - Объект',
                'verbose_name_plural': 'Справочники - Объекты',
            },
        ),
        migrations.RemoveField(
            model_name='weldingjoint',
            name='scheme',
        ),
        migrations.AddField(
            model_name='base',
            name='titul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Titul', verbose_name='Часть объекта, например, У800'),
        ),
        migrations.AddField(
            model_name='line',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Base', verbose_name='Установка в составе титула, например, '),
        ),
        migrations.AddField(
            model_name='line',
            name='scheme_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер изометрической схемы, например, 229-ВО-304SS-6" 2,5" C'),
        ),
        migrations.AddField(
            model_name='line',
            name='titul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Titul', verbose_name='Часть объекта, например, У800'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Компания, например, ТПС'),
        ),
        migrations.AlterField(
            model_name='titul',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Часть объекта, например, У800'),
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
        migrations.AddField(
            model_name='subject',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Company', verbose_name='Комания (объект), например ТПС'),
        ),
        migrations.AddField(
            model_name='linefile',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Line', verbose_name='Линия, например, 677-А2-LT-150'),
        ),
        migrations.AddField(
            model_name='titul',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Subject', verbose_name='Объект, например ТПС-ГФУ'),
        ),
    ]
