# Generated by Django 2.2.3 on 2020-07-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0013_auto_20200730_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingjoint',
            name='join_type',
        ),
        migrations.AddField(
            model_name='weldingjoint',
            name='join_type_from',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/переходник'),
        ),
        migrations.AddField(
            model_name='weldingjoint',
            name='join_type_to',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/труба'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='welding_conn_view',
            field=models.IntegerField(blank=True, choices=[(1, 'С17'), (2, 'У19'), (3, 'У20'), (4, 'С17/У20')], db_index=True, null=True, verbose_name='Вид сварного соединения, например, C17'),
        ),
        migrations.DeleteModel(
            name='JoinType',
        ),
    ]
