# Generated by Django 2.2.3 on 2020-07-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0014_auto_20200730_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingjoint',
            name='dinc',
        ),
        migrations.AddField(
            model_name='jointwelder',
            name='actually',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Фактический сварщик (тот, кто проводит работы), другие сващики могут быть указаны в заявках, потому что у фактических нет допуска'),
        ),
        migrations.AlterField(
            model_name='jointwelder',
            name='welding_joint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.WeldingJoint', verbose_name='Заявка на стык'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III')], db_index=True, null=True, verbose_name='Категория, например I'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='control_type',
            field=models.IntegerField(blank=True, choices=[(1, 'РК'), (2, 'УЗК'), (3, 'ВИК'), (4, 'РК-УЗК-ЦД'), (5, 'РК/УЗК'), (6, 'УК'), (7, 'ПВК')], db_index=True, null=True, verbose_name='Вид контроля, например, РК'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='join_type_from',
            field=models.IntegerField(blank=True, choices=[(1, 'труба'), (2, 'отвод'), (3, 'тройник'), (4, 'переходник'), (5, 'тройник'), (6, 'заглушка'), (7, 'фланец'), (8, 'штуцер'), (9, 'бобышка')], db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/переходник'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='join_type_to',
            field=models.IntegerField(blank=True, choices=[(1, 'труба'), (2, 'отвод'), (3, 'тройник'), (4, 'переходник'), (5, 'тройник'), (6, 'заглушка'), (7, 'фланец'), (8, 'штуцер'), (9, 'бобышка')], db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/труба'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'Новый стык'), (2, 'В работе'), (3, 'Готовый стык'), (4, 'В ремонте')], db_index=True, null=True, verbose_name='Статус заявки, например, в работе'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='workshift',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], db_index=True, null=True, verbose_name='Номер, смены, например, 1'),
        ),
    ]
