# Generated by Django 2.2.3 on 2020-07-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0015_auto_20200730_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingjoint',
            name='base',
        ),
        migrations.RemoveField(
            model_name='weldingjoint',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
