# Generated by Django 2.2.3 on 2020-07-30 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0016_auto_20200730_2207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'company')},
        ),
    ]
