# Generated by Django 2.2.3 on 2020-08-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0019_auto_20200801_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointwelder',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Позиция (от 1 до 4)'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='join_type_from',
            field=models.IntegerField(blank=True, choices=[(1, 'труба'), (2, 'отвод'), (3, 'тройник'), (4, 'переходник'), (5, 'заглушка'), (6, 'фланец'), (7, 'штуцер'), (8, 'бобышка')], db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/переходник'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='join_type_to',
            field=models.IntegerField(blank=True, choices=[(1, 'труба'), (2, 'отвод'), (3, 'тройник'), (4, 'переходник'), (5, 'заглушка'), (6, 'фланец'), (7, 'штуцер'), (8, 'бобышка')], db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/труба'),
        ),
    ]
