# Generated by Django 2.2.3 on 2020-08-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200402_2127'),
        ('weld', '0024_auto_20200802_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeldingJointFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Позиция файла')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Files', verbose_name='Файл для линии')),
                ('welding_joint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.WeldingJoint', verbose_name='Заявка на стык')),
            ],
            options={
                'verbose_name': 'Сварочные соединения - Файл заявки на стык',
                'verbose_name_plural': 'Сварочные соединения - Файлы заявок на стык',
                'default_permissions': [],
            },
        ),
        migrations.DeleteModel(
            name='LineFile',
        ),
    ]
