# Generated by Django 2.2.3 on 2020-08-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0027_auto_20200807_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weldingjointfile',
            options={'verbose_name': 'Сварочные соединения - Файл заявки на стык', 'verbose_name_plural': 'Сварочные соединения - Файлы заявок на стык'},
        ),
    ]
