# Generated by Django 2.2.3 on 2020-08-09 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weld', '0030_auto_20200809_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdingkss',
            name='material',
            field=models.IntegerField(blank=True, choices=[(1, '09Г2С'), (2, '12Х18Н10Т'), (3, '08Х18Н10Т'), (4, 'A-358 Gr.316/316L')], db_index=True, null=True, verbose_name='Материал - сталь, например, 12Х18Н10Т'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='material',
            field=models.IntegerField(blank=True, choices=[(1, '09Г2С'), (2, '12Х18Н10Т'), (3, '08Х18Н10Т'), (4, 'A-358 Gr.316/316L')], db_index=True, null=True, verbose_name='Материал - сталь, например, 09Г2С'),
        ),
        migrations.CreateModel(
            name='JointConclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Время смены статуса')),
                ('defects', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Выявленные дефекты')),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, выполнивший контроль')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to=settings.AUTH_USER_MODEL, verbose_name='Начальник')),
                ('welding_joint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.WeldingJoint', verbose_name='Заявка на стык')),
            ],
            options={
                'verbose_name': 'Сварочные соединения - Заключение (акт) на стык',
                'verbose_name_plural': 'Сварочные соединения - Заключения (акты) на стыки',
            },
        ),
    ]
