# Generated by Django 2.2.3 on 2020-08-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0032_auto_20200810_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welder',
            name='company',
        ),
        migrations.AddField(
            model_name='welder',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Subject', verbose_name='Находится на объекте, например, ГФУ'),
        ),
    ]
