# Generated by Django 2.2.3 on 2020-08-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0033_auto_20200810_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customer',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Компания, наименование предприятия-заказчика, например, ООО "ИНК"'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contractor',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наименование генподрядной и строительной организации и ее ведомственная принадлежность, например, АО "Хоневелл"'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Компания, наименование предприятия-заказчика, например, ООО "Транспромстрой"'),
        ),
    ]
