# Generated by Django 2.2.3 on 2020-08-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0034_auto_20200810_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointconclusion',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата акта (заключения)'),
        ),
    ]
