# Generated by Django 2.2.3 on 2020-08-12 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weld', '0035_auto_20200810_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointconclusion',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='jointconclusion',
            name='defects',
        ),
        migrations.RemoveField(
            model_name='jointconclusion',
            name='director',
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='vik_controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vik_controller', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, выполнивший контроль ВИК'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='vik_defects',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Выявленные дефекты ВИК'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='vik_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vik_director', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель работ по визуальному и измерительному контролю'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='welding_type',
            field=models.IntegerField(blank=True, choices=[(1, 'аргонодуговой сваркой'), (2, 'дуговой сваркой')], db_index=True, null=True, verbose_name='Тип сварки, например, аргонодуговая'),
        ),
        migrations.AddField(
            model_name='titul',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Описание титула, например, Отделение печей нагрева'),
        ),
        migrations.AlterField(
            model_name='jointconclusion',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата актов/заключений'),
        ),
    ]
