# Generated by Django 2.2.3 on 2020-08-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0037_defectoscopist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointconclusion',
            name='vik_controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vik_controller', to='weld.Defectoscopist', verbose_name='Пользователь, выполнивший контроль ВИК'),
        ),
        migrations.AlterField(
            model_name='jointconclusion',
            name='vik_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vik_director', to='weld.Defectoscopist', verbose_name='Руководитель работ по визуальному и измерительному контролю'),
        ),
    ]
