# Generated by Django 2.2.3 on 2020-08-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0038_auto_20200812_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defectoscopist',
            options={'verbose_name': 'Контроль - Дефектоскопист', 'verbose_name_plural': 'Контроль - Дефектоскописты'},
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='vik_active',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Проведен ВИК (показываем в таблице, что проведен)'),
        ),
        migrations.AlterField(
            model_name='defectoscopist',
            name='notice',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='jointconclusion',
            name='welding_type',
            field=models.IntegerField(blank=True, choices=[(1, 'ручной аргонодуговой сваркой'), (2, 'ручной дуговой сваркой')], db_index=True, null=True, verbose_name='Тип сварки, например, аргонодуговая'),
        ),
    ]
