# Generated by Django 2.2.3 on 2020-08-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0040_auto_20200812_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointconclusion',
            name='rk_defectoscopist1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rk_defectoscopist1', to='weld.Defectoscopist', verbose_name='Стык принял по внешнему виду дефектоскопист'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='rk_defectoscopist2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rk_defectoscopist2', to='weld.Defectoscopist', verbose_name='Контроль произвел дефектоскопист'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='rk_defectoscopist3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rk_defectoscopist3', to='weld.Defectoscopist', verbose_name='Заключение выдал дефектоскопист'),
        ),
    ]
