# Generated by Django 2.2.3 on 2020-08-13 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0041_auto_20200813_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointconclusion',
            name='pvk_control_type',
            field=models.IntegerField(blank=True, choices=[(1, 'первичный'), (2, 'вторичный')], db_index=True, null=True, verbose_name='Вид контроля, например, вторичный'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='pvk_defectoscopist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvk_defectoscopist', to='weld.Defectoscopist', verbose_name='Дефектоскопист'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='pvk_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pvk_director', to='weld.Defectoscopist', verbose_name='Начальник ЛНК'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='pvk_state',
            field=models.IntegerField(blank=True, choices=[(1, 'Годен'), (2, 'Исправить'), (3, 'Вырезать')], db_index=True, null=True, verbose_name='Оценка качества'),
        ),
    ]
