# Generated by Django 2.2.3 on 2020-08-13 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0042_auto_20200813_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointconclusion',
            name='uzk_defectoscopist1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzk_defectoscopist1', to='weld.Defectoscopist', verbose_name='Стык принял по внешнему виду дефектоскопист'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='uzk_defectoscopist2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzk_defectoscopist2', to='weld.Defectoscopist', verbose_name='Контроль произвел дефектоскопист'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='uzk_defectoscopist3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzk_defectoscopist3', to='weld.Defectoscopist', verbose_name='Заключение выдал дефектоскопист'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='uzk_notice',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='uzk_ray_angle',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Угол ввода луча в градусах'),
        ),
        migrations.AddField(
            model_name='jointconclusion',
            name='uzk_sensitivity',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Условная чувствительность зарубка в мм'),
        ),
    ]
