# Generated by Django 2.2.3 on 2020-08-13 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0043_auto_20200813_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointconclusion',
            name='uzk_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzk_operator', to='weld.Defectoscopist', verbose_name='Оператор'),
        ),
    ]
