# Generated by Django 2.2.3 on 2020-08-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0044_jointconclusion_uzk_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointconclusion',
            name='uzk_state',
            field=models.IntegerField(blank=True, choices=[(1, 'Годен'), (2, 'Исправить'), (3, 'Вырезать')], db_index=True, null=True, verbose_name='Оценка качества'),
        ),
    ]
