# Generated by Django 2.2.3 on 2020-08-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0045_jointconclusion_uzk_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rkframes',
            options={'default_permissions': [], 'verbose_name': 'Сварочные соединения - Снимок на РК заключение', 'verbose_name_plural': 'Сварочные соединения - Снимки на РК заключения'},
        ),
        migrations.AlterModelOptions(
            name='weldingjoint',
            options={'permissions': (('in_progress', 'Просмотр заявок в работе'), ('repair', 'Просмотр заявок в ремонте')), 'verbose_name': 'Сварочное соединение - Бланк-заявка', 'verbose_name_plural': 'Сварочные соединения - Бланк-заявки'},
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='control_type',
            field=models.IntegerField(blank=True, choices=[(1, 'РК'), (2, 'УЗК'), (3, 'ВИК'), (4, 'РК-ВИК'), (5, 'УК'), (6, 'РК-УЗК-ЦД'), (7, 'РК-УЗК'), (8, 'ПВК'), (9, 'МК'), (10, 'ВК'), (11, 'СР')], db_index=True, null=True, verbose_name='Вид контроля, например, РК'),
        ),
    ]
