# Generated by Django 2.2.3 on 2020-08-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0046_auto_20200813_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingjoint',
            name='conclusion_number',
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='join_type_from',
            field=models.IntegerField(blank=True, choices=[(1, 'труба'), (2, 'отвод'), (3, 'тройник'), (4, 'переход'), (5, 'заглушка'), (6, 'фланец'), (7, 'штуцер'), (8, 'бобышка')], db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/переходник'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='join_type_to',
            field=models.IntegerField(blank=True, choices=[(1, 'труба'), (2, 'отвод'), (3, 'тройник'), (4, 'переход'), (5, 'заглушка'), (6, 'фланец'), (7, 'штуцер'), (8, 'бобышка')], db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/труба'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='notice',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Примечание, например, только ВИК'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Годен'), (4, 'В ремонте')], db_index=True, null=True, verbose_name='Статус заявки, например, в работе'),
        ),
        migrations.AlterField(
            model_name='weldingjointstate',
            name='from_state',
            field=models.IntegerField(blank=True, choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Годен'), (4, 'В ремонте')], db_index=True, null=True, verbose_name='Статус заявки, например, в работе'),
        ),
        migrations.AlterField(
            model_name='weldingjointstate',
            name='to_state',
            field=models.IntegerField(blank=True, choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Годен'), (4, 'В ремонте')], db_index=True, null=True, verbose_name='Статус заявки, например, в работе'),
        ),
    ]
