# Generated by Django 2.2.3 on 2020-08-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0047_auto_20200814_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weldingjoint',
            name='joint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Joint', verbose_name='Номер стыка, например, 26А'),
        ),
    ]
