# Generated by Django 2.2.3 on 2020-08-19 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0048_auto_20200819_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weldingjoint',
            name='joint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint', to='weld.Joint', verbose_name='Номер стыка, например, 26А'),
        ),
    ]
