# Generated by Django 2.2.3 on 2020-08-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0050_auto_20200819_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='weldingjoint',
            name='dinc',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=9, null=True, verbose_name='D-inc, например, 6.30, нужен для отчетов, рассчитывается динамически, например, диаметр(160)/константа(25.4)=6.30'),
        ),
    ]
