# Generated by Django 2.2.3 on 2020-08-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0051_weldingjoint_dinc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingjoint',
            name='cutout',
        ),
    ]
