# Generated by Django 2.2.3 on 2020-08-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0052_remove_weldingjoint_cutout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingjoint',
            name='conclusion_date',
        ),
        migrations.AlterField(
            model_name='jointconclusion',
            name='welding_joint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joint_conclusion', to='weld.WeldingJoint', verbose_name='Заявка на стык'),
        ),
    ]
