# Generated by Django 2.2.3 on 2020-08-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0054_auto_20200819_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weldingjointstate',
            options={'permissions': (('repair_completed', 'Смена статуса - Ремонт выполнен'),), 'verbose_name': 'Сварочные соединения - Смена статуса заявки на стык', 'verbose_name_plural': 'Сварочные соединения - Смена статусов заявкок на стыки'},
        ),
    ]
