# Generated by Django 2.2.3 on 2020-08-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20200809_1025'),
        ('weld', '0056_auto_20200821_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointconclusion',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'Годен'), (2, 'Ремонт'), (3, 'Вырез'), (4, 'УЗК'), (5, 'Пересвет'), (6, 'Брак')], db_index=True, null=True, verbose_name='Результат заключения'),
        ),
        migrations.AlterField(
            model_name='weldingjointfile',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Files', verbose_name='Файл для заявки на стык'),
        ),
        migrations.CreateModel(
            name='JointConclusionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Позиция файла')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Files', verbose_name='Файл для заключения')),
                ('joint_conclusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.JointConclusion', verbose_name='Заключение на заявку на стык')),
            ],
            options={
                'verbose_name': 'Сварочные соединения - Файл заключения на заявку',
                'verbose_name_plural': 'Сварочные соединения - Файлы заключений на заявки',
            },
        ),
    ]
