# Generated by Django 2.2.3 on 2020-08-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0057_auto_20200822_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='titul',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Шифр титула'),
        ),
        migrations.AlterField(
            model_name='weldingjoint',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'Новый'), (2, 'На контроле ЗНК'), (3, 'Годен'), (4, 'В ремонте'), (5, 'Заявка отклонена')], db_index=True, null=True, verbose_name='Статус заявки, например, в работе'),
        ),
        migrations.AlterField(
            model_name='weldingjointstate',
            name='from_state',
            field=models.IntegerField(blank=True, choices=[(1, 'Новый'), (2, 'На контроле ЗНК'), (3, 'Годен'), (4, 'В ремонте'), (5, 'Заявка отклонена')], db_index=True, null=True, verbose_name='Статус заявки, например, в работе'),
        ),
        migrations.AlterField(
            model_name='weldingjointstate',
            name='to_state',
            field=models.IntegerField(blank=True, choices=[(1, 'Новый'), (2, 'На контроле ЗНК'), (3, 'Годен'), (4, 'В ремонте'), (5, 'Заявка отклонена')], db_index=True, null=True, verbose_name='Статус заявки, например, в работе'),
        ),
    ]
