# Generated by Django 2.2.3 on 2020-08-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0058_auto_20200825_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectoscopist',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Полное имя, например, Проскоков Никита Владимирович'),
        ),
        migrations.AlterField(
            model_name='defectoscopist',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'Начальник лаборатории'), (2, 'Дефектоскопист'), (3, 'Ведущий специалист ЛНК')], db_index=True, null=True, verbose_name='Должность'),
        ),
    ]
