# Generated by Django 2.2.3 on 2020-09-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0062_jointconclusion_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointconclusion',
            name='parent',
        ),
        migrations.AlterField(
            model_name='jointconclusion',
            name='welding_joint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joint_conclusion', to='weld.WeldingJoint', verbose_name='Заявка на стык'),
        ),
    ]
