# Generated by Django 2.2.3 on 2020-09-07 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0064_auto_20200907_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='certsections',
            name='welder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Welder', verbose_name='Сварщик'),
        ),
    ]
