# Generated by Django 2.2.3 on 2020-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0065_certsections_welder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rkframes',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер снимка, координаты мерного пояса, например, 0-300'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наименование сооружаемого объекта, например, Усть-Кутская газофракционирующая установка'),
        ),
    ]
