# Generated by Django 2.2.3 on 2020-09-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0066_auto_20200911_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='best_before',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='НАКС годен до, например, 27/04/20'),
        ),
    ]
