# Generated by Django 2.2.3 on 2020-09-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0067_certification_best_before'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NAX',
        ),
    ]
