# Generated by Django 2.2.3 on 2020-09-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0068_delete_nax'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='place',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Место удостоверения'),
        ),
    ]
