# Generated by Django 2.2.3 on 2020-09-16 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0069_certification_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'Сварщики - Удостоверение', 'verbose_name_plural': 'Сварщики - Удостоверения'},
        ),
        migrations.RemoveField(
            model_name='holdingkss',
            name='spent_length',
        ),
        migrations.AddField(
            model_name='holdingkss',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Certification', verbose_name='Удостоверение, на которое проводим КСС'),
        ),
        migrations.AddField(
            model_name='holdingkss',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата акта ВИК (совпадает с УЗК/РК)'),
        ),
        migrations.AddField(
            model_name='holdingkss',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weld.Subject', verbose_name='Место проведения КСС (объект)'),
        ),
        migrations.AddField(
            model_name='holdingkss',
            name='test_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер акта ВИК или УЗК/РК, например, 931'),
        ),
        migrations.AddField(
            model_name='holdingkss',
            name='with_rk',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Проведен РК'),
        ),
        migrations.AddField(
            model_name='holdingkss',
            name='with_uzk',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Проведен УЗК'),
        ),
        migrations.AlterField(
            model_name='holdingkss',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер КСС, например, КСС-195/2'),
        ),
        migrations.AlterField(
            model_name='holdingkss',
            name='state',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
