# Generated by Django 2.2.3 on 2020-09-19 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20200809_1025'),
        ('weld', '0072_auto_20200918_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Позиция файла')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Files', verbose_name='Файл для линии')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Структура - Файл для линии',
                'verbose_name_plural': 'Структура - Файлы для линий',
            },
        ),
    ]
