# Generated by Django 2.2.3 on 2020-09-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0073_linefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingjoint',
            name='welding_type',
        ),
        migrations.AddField(
            model_name='joint',
            name='welding_type',
            field=models.IntegerField(blank=True, choices=[(1, 'РАД'), (2, 'РД'), (3, 'РАД - РД')], db_index=True, null=True, verbose_name='Тип сварки, например, РД'),
        ),
    ]
