# Generated by Django 2.2.3 on 2020-09-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0074_auto_20200923_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingjoint',
            name='join_type_from',
        ),
        migrations.RemoveField(
            model_name='weldingjoint',
            name='join_type_to',
        ),
        migrations.RemoveField(
            model_name='weldingjoint',
            name='material',
        ),
        migrations.RemoveField(
            model_name='weldingjoint',
            name='welding_conn_view',
        ),
        migrations.AddField(
            model_name='joint',
            name='join_type_from',
            field=models.IntegerField(blank=True, choices=[(1, 'труба'), (2, 'отвод'), (3, 'тройник'), (4, 'переход'), (5, 'заглушка'), (6, 'фланец'), (7, 'штуцер'), (8, 'бобышка')], db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/переходник'),
        ),
        migrations.AddField(
            model_name='joint',
            name='join_type_to',
            field=models.IntegerField(blank=True, choices=[(1, 'труба'), (2, 'отвод'), (3, 'тройник'), (4, 'переход'), (5, 'заглушка'), (6, 'фланец'), (7, 'штуцер'), (8, 'бобышка')], db_index=True, null=True, verbose_name='Свариваемые элементы, например, тройник/труба'),
        ),
        migrations.AddField(
            model_name='joint',
            name='material',
            field=models.IntegerField(blank=True, choices=[(1, '09Г2С'), (2, '12Х18Н10Т'), (3, '08Х18Н10Т'), (4, 'A-358 Gr.316/316L')], db_index=True, null=True, verbose_name='Материал - сталь, например, 09Г2С'),
        ),
        migrations.AddField(
            model_name='joint',
            name='welding_conn_view',
            field=models.IntegerField(blank=True, choices=[(1, 'С17'), (2, 'У19'), (3, 'У20'), (4, 'С17/У20'), (5, 'У18')], db_index=True, null=True, verbose_name='Вид сварного соединения, например, C17'),
        ),
    ]
