# Generated by Django 2.2.3 on 2020-09-28 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0076_auto_20200925_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointwelder',
            name='welding_joint',
        ),
        migrations.AddField(
            model_name='jointwelder',
            name='joint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weld.Joint', verbose_name='Стык'),
        ),
    ]
