# Generated by Django 2.2.3 on 2020-02-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, null=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timetable', models.TextField(blank=True, null=True, verbose_name='Таблица времени')),
            ],
            options={
                'verbose_name': 'Сервисы - Расписание для демона',
                'verbose_name_plural': 'Сервисы - Расписания для демонов',
            },
        ),
        migrations.AlterField(
            model_name='daemon',
            name='exec_path',
            field=models.CharField(blank=True, choices=[('binary_com/binary_bot.py', 'Бинарные опционы')], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='daemon',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Параметры для запуска: args'),
        ),
    ]
