# Generated by Django 2.2.3 on 2020-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonology', '0004_auto_20200406_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Завершение события'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'BINARY - Bollinger strategy')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Начало события'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
