# Generated by Django 2.2.3 on 2020-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonology', '0005_auto_20200406_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemon',
            name='api_url',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Стратегия Bollinger'), (2, 'Стратегия Random')], db_index=True, null=True),
        ),
    ]
