# Generated by Django 2.2.3 on 2020-06-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonology', '0006_auto_20200406_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
