# Generated by Django 2.2.3 on 2020-10-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonology', '0007_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemon',
            name='exec_path',
            field=models.CharField(blank=True, choices=[('binary_com/binary_bot.py', 'Бинарные опционы'), ('spamcha/sms_hub.py', 'Телефоны для смс')], db_index=True, max_length=255, null=True),
        ),
    ]
