# Generated by Django 2.2.3 on 2021-03-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0004_config_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Админка - Настройка', 'verbose_name_plural': 'Админка - Настройки'},
        ),
    ]
