# Generated by Django 2.2.3 on 2021-11-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functions', '0005_auto_20210321_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Сгенерированная строка')),
            ],
        ),
    ]
