# Generated by Django 2.2.3 on 2019-12-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'verbose_name': 'Рассылка - Аккаунты', 'verbose_name_plural': 'Рассылка - Аккаунты'},
        ),
        migrations.AlterModelOptions(
            name='emailblacklist',
            options={'verbose_name': 'Рассылка - Черный список', 'verbose_name_plural': 'Рассылка - Черный список'},
        ),
        migrations.AlterModelOptions(
            name='spamrow',
            options={'verbose_name': 'Рассылка - Записи в таблицах рассылок', 'verbose_name_plural': 'Рассылка - Записи в таблицах рассылок'},
        ),
        migrations.AlterModelOptions(
            name='spamtable',
            options={'verbose_name': 'Рассылка - Таблицы рассылки', 'verbose_name_plural': 'Рассылка - Таблицы рассылки'},
        ),
    ]
