# Generated by Django 2.2.3 on 2020-09-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcha', '0003_auto_20200112_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название телефона, например, Samsung Galaxy A5')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер телефона, например, 89501100222')),
                ('code', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ИД телефона, например, 123321')),
            ],
            options={
                'verbose_name': 'Рассылка - Телефон для смс',
                'verbose_name_plural': 'Рассылка - Телефоны для смс',
            },
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='emailblacklist',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='spamrow',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='spamtable',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
