# Generated by Django 2.2.3 on 2020-09-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcha', '0004_auto_20200908_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsphone',
            name='limit',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Максимальное кол-во для отправки'),
        ),
        migrations.AddField(
            model_name='smsphone',
            name='sent',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Кол-во отправленных смс'),
        ),
    ]
