# Generated by Django 2.2.3 on 2020-12-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcha', '0005_auto_20200908_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='spamrow',
            name='client_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Ид получателя (для связи с CRM)'),
        ),
        migrations.AddField(
            model_name='spamrow',
            name='client_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Официальное название получателя (возможно, из CRM)'),
        ),
    ]
