# Generated by Django 2.2.3 on 2020-06-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='discount_info',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Информация по скидке'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='product_manufacturer',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='product_measure',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Оригинальная цена без скидок'),
        ),
    ]
