# Generated by Django 2.2.3 on 2020-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200618_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='shopper',
        ),
        migrations.RenameField(
            model_name='purchases',
            old_name='user',
            new_name='shopper',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='shopper',
        ),
        migrations.AddField(
            model_name='orders',
            name='shopper_address',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='shopper_email',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='shopper_ip',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='shopper_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='shopper_phone',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
