# Generated by Django 2.2.3 on 2020-06-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200623_1629'),
        ('shop', '0003_auto_20200621_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.CostsTypes'),
        ),
    ]
