# Generated by Django 2.2.3 on 2020-07-19 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_shopper_ip'),
        ('shop', '0005_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Магазин - Покупки', 'verbose_name_plural': 'Магазин - Покупки'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Магазин - Транзакция', 'verbose_name_plural': 'Магазин - Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'default_permissions': [], 'verbose_name': 'Магазин - Избранное', 'verbose_name_plural': 'Магазин - Избранное'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='cost',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=13, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='product_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=13, null=True, verbose_name='Оригинальная цена без скидок'),
        ),
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название промокода')),
                ('percent', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Процентная скидка по промо-коду')),
                ('value', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Скидка на сумму')),
                ('code', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Промокод')),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Начало действия')),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Окончание действия')),
                ('use_count', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Ограничение на кол-во применений')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.Shopper', verbose_name='Промокод для конкретного пользователя (персональный)')),
            ],
            options={
                'verbose_name': 'Магазин - Промокод',
                'verbose_name_plural': 'Магазин - Промокоды',
            },
        ),
    ]
