# Generated by Django 2.2.3 on 2020-10-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200719_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='success',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
