# Generated by Django 2.2.3 on 2020-12-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201026_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='product_min_count',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Минимальное кол-во товара для заказа'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='product_multiplicity',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Кратность товара (кол-во добавляемого товара в корзину)'),
        ),
    ]
