# Generated by Django 2.2.3 on 2021-02-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201212_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payed',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=13, null=True, verbose_name='Оплаченная сумма'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='ptype',
            field=models.IntegerField(blank=True, choices=[(1, 'YandexKassa'), (2, 'Сбербанк')], db_index=True, null=True),
        ),
    ]
