# Generated by Django 2.2.3 on 2021-08-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_ordersdelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersdelivery',
            options={'verbose_name': 'Магазин - Доставка заказа', 'verbose_name_plural': 'Магазин - Доставки заказов'},
        ),
    ]
