# Generated by Django 2.2.3 on 2021-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210801_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdelivery',
            name='additional_data',
            field=models.TextField(blank=True, null=True, verbose_name='json ина с доп данными'),
        ),
    ]
