# Generated by Django 2.2.3 on 2021-01-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наименование контрагента')),
                ('code', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Код контрагента')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Телефон контрагента')),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email контрагента')),
                ('ctype', models.IntegerField(blank=True, choices=[(1, 'Физическое лицо'), (2, 'Индивидуальный предприниматель'), (3, 'Юридическое лицо')], db_index=True, null=True, verbose_name='Тип контрагента')),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Наименование компании')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='КПП контрагента')),
                ('ogrn', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ОГРН контрагента')),
                ('okpo', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ОКПО контрагента')),
                ('bik', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='БИК')),
                ('bank', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Банк')),
                ('ks', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Корр. счет')),
                ('rs', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Расчетный счет')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Отчество')),
                ('certificate_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Номер свидетельства')),
                ('certificate_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата свидетельства')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='addresses.Address', verbose_name='Физический адрес контрагента')),
                ('bank_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_address', to='addresses.Address', verbose_name='Адрес банка')),
                ('legal_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_address', to='addresses.Address', verbose_name='Юридический адрес контрагента')),
            ],
            options={
                'verbose_name': 'Контрагенты - Контрагент',
                'verbose_name_plural': 'Контрагенты - Контрагенты',
            },
        ),
    ]
