# Generated by Django 2.2.3 on 2019-12-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, null=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Чат - Группы',
                'verbose_name_plural': 'Чат - Группы',
            },
        ),
        migrations.AlterModelOptions(
            name='bcastmessages',
            options={'verbose_name': 'Чат - Широковещательные сообщения', 'verbose_name_plural': 'Чат - Широковещательные сообщения'},
        ),
        migrations.AlterModelOptions(
            name='conversations',
            options={'verbose_name': 'Чат - Беседы', 'verbose_name_plural': 'Чат - Беседы'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Чат - Сообщения', 'verbose_name_plural': 'Чат - Сообщения'},
        ),
        migrations.AddField(
            model_name='conversations',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ws.ConversationGroup'),
        ),
    ]
