# Generated by Django 2.2.3 on 2020-01-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws', '0004_conversationgroup_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
