# Generated by Django 2.2.3 on 2023-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miners', '0002_comp_token_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='pcb_sn',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
