# Generated by Django 2.2.3 on 2020-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('state', models.IntegerField(blank=True, db_index=True, null=True)),
                ('parents', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('passwd', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('oauth', models.IntegerField(blank=True, choices=[(1, 'vk')], db_index=True, null=True)),
                ('discont', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Персональная скидка')),
                ('balance', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=13, null=True, verbose_name='Баланс пользователя')),
            ],
            options={
                'verbose_name': 'Пользователи - пользователь',
                'verbose_name_plural': 'Пользователи - пользователи',
            },
        ),
    ]
