# Generated by Django 2.2.3 on 2020-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopper',
            old_name='discont',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='shopper',
            name='login',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='oauth',
            field=models.IntegerField(blank=True, choices=[(1, 'обычная авторизация'), (2, 'vk')], db_index=True, null=True),
        ),
    ]
