# Generated by Django 2.2.3 on 2020-06-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200528_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='oauth',
            field=models.IntegerField(blank=True, choices=[(1, 'обычная авторизация'), (2, 'vk'), (3, 'yandex')], db_index=True, null=True),
        ),
    ]
