# Generated by Django 2.2.3 on 2020-06-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20200616_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='ip',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ip адрес пользователя'),
        ),
    ]
