# Generated by Django 2.2.3 on 2021-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_shopper_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='phone_confirmed',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Телефон подтвержден'),
        ),
    ]
