# Generated by Django 2.2.3 on 2020-04-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flattooltip', '0003_flattooltip_img_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='flattooltip',
            name='direction',
            field=models.IntegerField(blank=True, choices=[(2, 'Слева'), (4, 'Справа')], db_index=True, null=True, verbose_name='Направление/размещение подсказки'),
        ),
    ]
