# Generated by Django 2.2.3 on 2020-04-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatcontent', '0007_auto_20200402_2127'),
        ('flattooltip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flattooltip',
            options={'verbose_name': 'Подсказки - Подсказка', 'verbose_name_plural': 'Подсказки - Подсказки'},
        ),
        migrations.AddField(
            model_name='flattooltip',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flatcontent.Blocks'),
        ),
        migrations.AddField(
            model_name='flattooltip',
            name='xpos',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='flattooltip',
            name='ypos',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
