# Generated by Django 2.2.3 on 2020-04-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flattooltip', '0002_auto_20200411_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='flattooltip',
            name='img_size',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
