# Generated by Django 2.2.3 on 2019-12-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Стат.контет - Файлы', 'verbose_name_plural': 'Стат.контент - Файлы'},
        ),
    ]
