# Generated by Django 2.2.3 on 2020-08-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200402_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Стат.контет - Файл', 'verbose_name_plural': 'Стат.контент - Файлы'},
        ),
    ]
